services:
  backend:
    build: ./backend
    environment:
      - FILES_DIR=/files
      - CORS_ORIGINS=*
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - DEFAULT_AI_MODEL=${DEFAULT_AI_MODEL:-gpt-5}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-http://host.docker.internal:11434/v1}
    env_file:
      - .env
    volumes:
      - ./files:/files
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
